### ISSUE TITLE
v2.0.0 Checklist

### ISSUE THREAD

**Issue by sudoio** [sudoio/fast-electron#1]
## Window
- [x] Implement `open(window, directory, filename)`.
## Shortcuts
- [x] Change `getCtrlShortcutWithKey()` to `ctrl()`
- [x] Implement `alt()` function
## Menu
- [x] Improve Developer Tools
